default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gw2oracle_dev

test:
  <<: *default
  database: gw2oracle_test

production:
  <<: *default
  database: gw2oracle
  username: gw2
